# Generated by Django 4.1.7 on 2023-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('email', models.EmailField(default='', max_length=50, null=True)),
                ('password', models.CharField(default='', max_length=10, null=True)),
                ('cpassword', models.CharField(default='', max_length=10, null=True)),
                ('mobile', models.CharField(default='', max_length=10, null=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
                ('role', models.CharField(default='', max_length=10, null=True)),
                ('city', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
