# Generated by Django 4.1.7 on 2023-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
